### ISSUE TITLE
Got jq: error (at <unknown>): Cannot index string with string "metrics" Error for one of Support Script

### ISSUE THREAD

**Issue by henrywangpuppet** [puppetlabs/support-script-analyzer#3] opened 2021-01-15 14:51 UTC
```
support-script-analyzer git:(master) ./support_parse.sh tech_check ~/Downloads/puppet_enterprise_support_42639_mme-1a-puppet-873_20210107230655.tar.gz
jq: error (at <unknown>): Cannot index string with string "metrics" Error for one of Support Script
...
...
<following with normal tech check>
```
The support script is from ticket 42639 on Box.com.

**Comment by m0dular** [comment] 2021-03-15 17:24
I think this is essentially a duplicate of #7, so I'll close this in favor of that one.

**Closed as completed by m0dular** 2021-03-15 17:24 UTC
Labels: bug
